<div class="row">
    <div class="col-xs-6 col-md-4">
        <form role="form" class="form-signin">
            <h2 class="form-signin-heading">Please sign in</h2>
            <input type="text" autofocus="" required="" placeholder="Email address" class="form-control">
            <input type="password" required="" placeholder="Password" class="form-control">
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
        </form>
    </div>
</div>